export const enviroment = {
  supabaseUrl: "https://sqojjljzdysfynfvsiwx.supabase.co",
  supabaseKey: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxb2pqbGp6ZHlzZnluZnZzaXd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzkxNjY0MjUsImV4cCI6MjA5NDc0MjQyNX0.16qY0FKcDiqnUdPl2Vpzhp8kzkxiYWD1LumGXX_qRQY"
}
